### ISSUE TITLE
Issue installing pytransloadit

### ISSUE THREAD

**Issue by MadReal** [transloadit/python-sdk#3]
Hello, I'm having issues install pytransloadit with pip.
It's giving me this

```
Collecting pytransloadit
  Using cached pytransloadit-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l8/3l7c5px141140t1lc2_qcv040000gn/T/pip-build-ud0eqbr1/pytransloadit/setup.py", line 12, in <module>
        long_description = pypandoc.convert('README.md', 'rst').replace("\r", "")
      File "/Users/madreal/Sites/clickandrap_django/venv/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l8/3l7c5px141140t1lc2_qcv040000gn/T/pip-build-ud0eqbr1/pytransloadit/
```

I tried also installing `pypandoc` first but no difference

**Comment by ifedapoolarewaju** [comment]
@MadReal fixed, please install version `0.1.5` by running `pip install pytransloadit==0.1.5`.
I'll close this ticket now, but please feel free to re-open if the issue persists 🙂

**Comment by vmihalachi** [comment]
Hi @ifedapoolarewaju, I still get an issue with pypandoc when trying to install this lib.

`Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9b/z6qdt7sd0f57f2kks8bx1w3h0000gp/T/pip-build-i45_n4vt/pytransloadit/setup.py", line 12, in <module>
        long_description = pypandoc.convert('README.md', 'rst').replace("\r", "")
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 69, in convert
        outputfile=outputfile, filters=filters)
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 260, in _convert_input
        _ensure_pandoc_path()
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 544, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.`

I used pip3 install pypandoc, should I have used brew (on macOS) instead? 
Thanks

**Comment by ifedapoolarewaju** [comment]
@vmihalachi fixed and released 🙂

**Comment by vmihalachi** [comment]
@ifedapoolarewaju yep, thank you!

**Comment by MadReal** [comment]
@ifedapoolarewaju there are still issues, 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1866, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1330, in do_init
    do_lock(system=system, pre=pre)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/utils.py", line 461, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/l8/3l7c5px141140t1lc2_qcv040000gn/T/tmpeabuw828build/pytransloadit/
```
to make the installation work one has to install `pypandoc` first and than install the rest of the dep

**Comment by ifedapoolarewaju** [comment]
@MadReal thank you for reporting. I somehow forgot to remove [this](https://github.com/transloadit/python-sdk/blob/v0.1.6/setup.py#L2). I have fixed it and published a release once again. For the last time I hope 🤞
